Theme refactor (attempt 2)
syphon-org/syphon pull request #274
Opened 2021-06-29 17:26 UTC by 0x1a8510f2

### Types
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (fix or feature that would cause existing functionality to not work as expected)
- [ ] Breaking change (non-breaking change which improves code quality - QA thoroughly)

### Changes

#### 🔮 Features
#### 🔒 Security 
#### 🛠 Performance
#### 🐛 Fixes
- [ ] Fix #270 (FAB should change colour at the same time as everything else)
- [ ] Sort out system UI transparency
#### 📐 Refactoring
- [x] Create `theme-settings` to keep theme stuff in one place
- [ ] Tweak everything to use the new `theme-settings`
- [ ] Ensure system and app themes don't get out of sync by setting them simultaneously
- [ ] Cleanup

### Media (if applicable)
    
### QA

- [ ] Signup
- [ ] Login
- [ ] Logout
- [ ] Unencrypted Chat 
- [ ] Encrypted Chat 
- [ ] Group Chats
- [ ] Profile Changes
- [ ] Theming Changes
- [ ] Force Kill and Restart

### Final Checklist
 
- [ ] All associated issues have been linked to PR
- [ ] All necessary changes made to the documentation
- [ ] Parties interested in these changes have been notified

2021-06-29 17:42 UTC, 0x1a8510f2 commented
I've quickly transferred over the changes from my previous PR, and I think this should be ready for review now. There may be a little more cleanup to do, so this should probably not be merged just yet, but it does build, and I think I'm ready to get some feedback :D

2021-07-01 12:55 UTC, ereio approved these changes
Everything looks great! Added some feedback, but the potential changes are not blocking an approval or merge. Let me know if you'd like to make any additional changes based on the comments, otherwise I'll approve / merge :)

2021-07-01 12:55 UTC, ereio commented on lib/global/themes.dart
> +      fontFamily: enumToString(appTheme.fontName),
Consider declaring `final fontFamily = enumToString(appTheme.fontName)` above alongside the other selectors

2021-07-01 12:55 UTC, ereio commented on lib/views/home/groups/group-create-screen.dart
> +          final backgroundColor = selectBackgroundBrightness(props.themeType);
_Note To Myself_

extract background color to the props level

2021-07-01 12:55 UTC, ereio commented on lib/views/home/settings/settings-screen.dart
> +        fontName: enumToString(store.state.settingsStore.appTheme.fontName),
Consider making a selector for `fontName` that has `enumToString` contained within

2021-07-01 12:55 UTC, ereio commented on lib/views/home/settings/settings-theming-screen.dart
> +        fontName: enumToString(store.state.settingsStore.appTheme.fontName),
Just an additional note on creating selectors for these `enumToString` conversions

If every consumer of the data (ThemeData, Widgets in Screens, etc) is always going to required a `String` type, we should make a `selector*` for it to encapsulate the enum conversion.

2021-07-01 18:20 UTC, 0x1a8510f2 commented on lib/store/settings/theme-settings/model.dart
> +class AppTheme extends Equatable {
Ah, that does make sense. On it! Should I also rename the `SettingsStore` property `appTheme` to match?

2021-07-01 18:32 UTC, 0x1a8510f2 commented on lib/global/themes.dart
> +      fontFamily: enumToString(appTheme.fontName),
I noticed that I've actually got quite a mix here, with some being declared above, and some, like `fontFamily` and `dialogBackgroundColor` being done inline. The reason for that was previously that I wanted to avoid running getters multiple times if a value was used multiple times (I assumed that was not optimised away). However, now that we're using selectors, I believe the results of those are cached anyway so they are evaluated only once for each value. Hence, would you say it's better to put everything in the final declarations at the top or to just put everything inline?

2021-07-01 18:34 UTC, 0x1a8510f2 commented on lib/views/home/settings/settings-screen.dart
> +        fontName: enumToString(store.state.settingsStore.appTheme.fontName),
Sure! Should I do that for all theme-related uses of `enumToString` for consistency or just `fontName`?

2021-07-02 20:48 UTC, 0x1a8510f2 commented
I've included all the changes from review now, and after another quick glance, all seems to be looking well. I've also included the fix from #273 which I accidentally removed while transferring changes over, which should now mean no regressions :P.

There are some parts of the code which I was unsure about in terms of whether I should change them or not. For instance, the [border radius calculations in `avatar.dart`](https://github.com/syphon-org/syphon/blob/6d7712d49945c42167ca18a6df704fda8ccf50b0/lib/views/widgets/avatars/avatar.dart#L47). I figured those could also be moved to selectors which would conveniently put everything in one spot. In the end, I decided not to touch those since I'm not sure exactly how many instances of similar things there are across the codebase, and changing one could end up in an inconsistent mess if I don't find the others. Plus, my branch was getting increasingly out of sync with main, so might be best to leave that part until a later date and get the current work merged first.

In general, as long as you're happy with the changes since review, I think we're ready to merge :D

2021-07-02 23:31 UTC, ereio commented
running a final QA and then I'll merge 👍

2021-07-02 23:44 UTC, ereio requested changes

2021-07-02 23:44 UTC, ereio commented on lib/global/themes.dart
> -      colorScheme: ThemeData().colorScheme.copyWith(
Sorry, noticed one more thing during the QA run. We do need to set `colorScheme` here. Setting `colorScheme` here is what prevents accent colors from acting strange in 2.2.0+, which was what caused the discoloration of the input fields on login

2021-07-03 10:19 UTC, 0x1a8510f2 commented on lib/global/themes.dart
> -      colorScheme: ThemeData().colorScheme.copyWith(
Ah, I noticed that issue actually but forgot to look into it. I didn't deliberately remove this part, it's just that I copy+pasted this entire file from my previous PR because I assumed it hasn't changed much, and that file didn't yet have this part. Will fix :D

2021-07-03 13:24 UTC, ereio approved these changes

2021-07-03 13:24 UTC, merged