Feature: HTTP Proxy
syphon-org/syphon pull request #416
Opened 2021-11-21 20:18 UTC by EdGeraghty

### Types
- [ ] Fix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking change which improves code quality - QA thoroughly )
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)

### Changes

#### 🔮 Features
Allow the specifying of an HTTP proxy on Mobile
#### 🔒 Security 
#### 🛠 Performance
#### 🐛 Fixes
#### 📐 Refactoring

### Media (if applicable)
    
### QA

- [ ] Signup
- [ ] Login
- [ ] Logout
- [ ] Unencrypted Chat 
- [ ] Encrypted Chat 
- [ ] Group Chats
- [ ] Profile Changes
- [ ] Theming Changes
- [ ] Force Kill and Restart

### Final Checklist
 
- [ ] All associated issues have been linked to PR
- [ ] All necessary changes made to the documentation
- [ ] Parties interested in these changes have been notified

2021-11-21 21:26 UTC, EdGeraghty commented
Starting work on #415

2021-11-25 18:10 UTC, EdGeraghty commented
This code needs ` TextEditingController ` to be patched, but I believe otherwise works

2021-11-26 18:22 UTC, ereio requested changes

2021-11-26 18:22 UTC, ereio commented on lib/global/libs/matrix/media.dart
> -    httpClient = createClient();
These are necessary to run these functions in a background thread. Each isolate in Dart has no context or shared RAM from another, similar to NodeJS. They're not "threads" proper.

2021-11-26 18:22 UTC, ereio commented on lib/global/libs/matrix/media.dart
> -    httpClient = createClient();
note previous comment

2021-11-26 18:22 UTC, ereio commented on lib/global/libs/matrix/rooms.dart
> -    httpClient = createClient();
note previous comment

2021-11-26 18:22 UTC, ereio commented on lib/global/libs/matrix/events.dart
> -    httpClient = createClient();
note previous comment

2021-11-26 18:25 UTC, ereio requested changes

2021-11-26 18:25 UTC, ereio commented on lib/views/intro/login/login-screen.dart
> +              icon: Icon(Icons.vpn_lock),
Change to the overflow (...) icon instead, as we'll likely be placing out-of-band SMS here as well

2021-11-26 18:25 UTC, ereio commented on lib/store/settings/state.dart
> +import 'http-proxy-settings/model.dart';
Rename `HttpProxySettings` to just `ProxySettings` and the directory structure equivalent in kebab case `proxy-settings`

2021-11-26 19:40 UTC, EdGeraghty commented on lib/global/libs/matrix/media.dart
> -    httpClient = createClient();
Reverted the two referred commits

2021-11-26 19:41 UTC, EdGeraghty commented on lib/global/libs/matrix/media.dart
> -    httpClient = createClient();
reverted

2021-11-26 19:41 UTC, EdGeraghty commented on lib/global/libs/matrix/rooms.dart
> -    httpClient = createClient();
reverted

2021-11-26 19:41 UTC, EdGeraghty commented on lib/global/libs/matrix/events.dart
> -    httpClient = createClient();
reverted

2021-11-26 20:14 UTC, EdGeraghty commented on lib/views/intro/login/login-screen.dart
> +              icon: Icon(Icons.vpn_lock),
I went for the vertical one , as I think it looks better. Feel free to replace with horizontal

2021-11-26 22:55 UTC, ereio approved these changes
Everything looks good here code wise. Going to QA and fix the dialog issue, and if nothing else shows up, it's good to go.

2021-11-28 22:20 UTC, ereio requested changes

2021-11-28 22:20 UTC, ereio commented on lib/store/settings/proxy-settings/model.dart
> +  Map<String, dynamic> toJson() => _$HttpProxySettingsToJson(this);
Make sure to rename both the `*Json()` functions from `HttpProxySettings*` to `ProxySettings*`

2021-11-28 22:20 UTC, ereio commented on lib/store/settings/proxy-settings/model.dart
> +  Map<String, dynamic> toJson() => _$HttpProxySettingsToJson(this);
Sorry, testing this PR now and caught this after the fact

2021-11-28 22:29 UTC, EdGeraghty commented on lib/store/settings/proxy-settings/model.dart
> +  Map<String, dynamic> toJson() => _$HttpProxySettingsToJson(this);
Done. I missed them too.

2021-11-28 22:37 UTC, ereio commented
added a small PR to your fork that fixes the dialog inputs. Feel free to merge or re-implement the changes. I'll merge once  those are in. looks good!

2021-11-28 22:41 UTC, EdGeraghty commented
> added a small PR to your fork that fixes the dialog inputs. Feel free to merge or re-implement the changes. I'll merge once those are in. looks good!

Done!

Thanks!

2021-11-28 22:48 UTC, ereio approved these changes

2021-11-28 22:48 UTC, merged