chore: update contribution guidelines
syphon-org/syphon pull request #572
Opened 2022-02-18 19:42 UTC by EdGeraghty

### Types
- [ ] Fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking change which improves code quality - QA thoroughly )
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [x] Chore (updates that would not affect or change the code involving the app itself)

### Changes

#### 🔮 Features
#### 🐛 Fixes
#### 🔒 Security 
#### 🛠 Performance
#### 📐 Refactoring

### Media (if applicable)
    
### QA

- [ ] Signup
- [ ] Login
- [ ] Logout
- [ ] Unencrypted Chat 
- [ ] Encrypted Chat 
- [ ] Group Chats
- [ ] Profile Changes
- [ ] Theming Changes
- [ ] Force Kill and Restart

### Final Checklist
 
- [ ] All associated issues have been linked to PR
- [ ] All necessary changes made to the documentation
- [ ] Parties interested in these changes have been notified

2022-02-18 21:53 UTC, EdGeraghty commented
This commit is designed to clarify the copyright around Syphon.

If authors wish to add their names/handles to the AUTHOR file, that's their deal and certainly is not required.

2022-02-20 20:08 UTC, ereio requested changes

2022-02-20 20:08 UTC, ereio commented on AUTHORS
> +Syphon is written by (a non-exhaustive list, in alphabetical order):
would you mind renaming the file `authors.md`, all lowercase? or `authors.txt` if we don't intend to use markdown?

2022-02-20 22:38 UTC, ereio approved these changes

2022-02-20 22:38 UTC, merged