chore: Settings->Chats
syphon-org/syphon pull request #600
Opened 2022-02-25 17:41 UTC by EdGeraghty

### Types
- [ ] Fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [x] Refactor (non-breaking change which improves code quality - QA thoroughly )
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [x] Chore (updates that would not affect or change the code involving the app itself)

### Changes

#### 🔮 Features
#### 🐛 Fixes
#### 🔒 Security 
#### 🛠 Performance
#### 📐 Refactoring
Adding some more strings to the translation library
### Media (if applicable)
    
### QA

- [ ] Signup
- [ ] Login
- [ ] Logout
- [ ] Unencrypted Chat 
- [ ] Encrypted Chat 
- [ ] Group Chats
- [ ] Profile Changes
- [ ] Theming Changes
- [ ] Force Kill and Restart

### Final Checklist
 
- [ ] All associated issues have been linked to PR
- [ ] All necessary changes made to the documentation
- [ ] Parties interested in these changes have been notified

2022-03-07 02:02 UTC, ereio requested changes

2022-03-07 02:02 UTC, ereio commented on lib/store/sync/background/parsers.dart
> +    return Strings.notificationSentNewMessage(formattedSender);
Worried this may not work. Have you tested this works successfully?

Background threads in Flutter / Dart do not have the same context as the app. You'll need to initialize i18l before running the service job / thread. Lmk if you're tested with this working or not, I can take a look

2022-03-07 14:09 UTC, EdGeraghty commented on lib/store/sync/background/parsers.dart
> +    return Strings.notificationSentNewMessage(formattedSender);
You're correct that this doesn't work - `[🌎 Easy Localization] [WARNING] Localization key [notification-sent-message-in-room] not found`.

2022-03-18 17:05 UTC, ereio commented
did you get a chance to fix the notification translations? would you mind reverting those if not so we can merge the other work? would like to get the bulk of your work merged! :)

2022-03-18 17:58 UTC, ereio requested changes
Everything looks good but this one issue. Will approve afterwards!

2022-03-18 17:58 UTC, ereio commented on assets/translations/en.json
> +    "label-syncing-chats-chats": "syncing chats…",
should be just `label-syncing-chats` i think

2022-03-18 18:03 UTC, ereio approved these changes

2022-03-18 18:04 UTC, merged