[Feature] Only offer hidden read receipts if allowed by the homeserver
syphon-org/syphon pull request #647
Opened 2022-03-30 21:51 UTC by EdGeraghty

### Types
- [x] Fix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [x] Refactor (non-breaking change which improves code quality - QA thoroughly )
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore (updates that would not affect or change the code involving the app itself)

### Changes

#### 🔮 Features
Only offer hidden read receipts if allowed by the homeserver (Fixes #629)
#### 🐛 Fixes
#### 🔒 Security 
#### 🛠 Performance
#### 📐 Refactoring

### Media (if applicable)
    
### QA

- [ ] Signup
- [ ] Login
- [ ] Logout
- [ ] Unencrypted Chat 
- [ ] Encrypted Chat 
- [ ] Group Chats
- [ ] Profile Changes
- [ ] Theming Changes
- [ ] Force Kill and Restart

### Final Checklist
 
- [x] All associated issues have been linked to PR
- [ ] All necessary changes made to the documentation
- [ ] Parties interested in these changes have been notified

2022-03-31 13:38 UTC, ereio requested changes

2022-03-31 13:38 UTC, ereio commented on lib/store/settings/actions.dart
> +      store.dispatch(SetReadReceipts(
Would like to make the logic here a bit clearer. Try using guard clauses here to improve readability. I've added an example below

```dart
 if (nextReceipt != ReadReceiptTypes.Hidden) { //short-out
      return store.dispatch(SetReadReceipts(
        readReceipts: nextReceipt
      ));
 }
 
 if (await homeserverSupportsHiddenReadReceipts(store)) {
    return store.dispatch(SetReadReceipts(
      readReceipts: ReadReceiptTypes.Hidden,
     ));
  }
  
  store.dispatch(SetReadReceipts(
          readReceipts: ReadReceiptTypes.values[(readReceiptsIndex + 2) %
          ReadReceiptTypes.values.length],
   ));
```

2022-03-31 13:38 UTC, ereio commented
otherwise, this looks good!

2022-03-31 19:17 UTC, EdGeraghty commented on lib/store/settings/actions.dart
> +      store.dispatch(SetReadReceipts(
Ah, I didn't realise I could code it like that. Thanks for the example, I'll look at some point shortly

2022-03-31 19:23 UTC, notramo reviewed
Does it handle incomplete JSON?

2022-03-31 19:23 UTC, notramo commented on lib/store/settings/actions.dart
> +  final unstableFeatures = version['unstable_features'];
Sorry, I don't have time to dig deeper in the code. What does it do when there is no `unstable_features` key?
If it throws an exception, does it crash? Or display an unnecessary error popup?
Correct action would be to return `false`.

2022-04-01 10:07 UTC, EdGeraghty commented on lib/store/settings/actions.dart
> +  final unstableFeatures = version['unstable_features'];
good catch.

2022-04-01 16:32 UTC, ereio approved these changes

2022-04-01 16:32 UTC, ereio commented on lib/store/settings/actions.dart
> +  final unstableFeatures = version['unstable_features'];
A preferred alternative to the null check could also be adding a non-null var default. You'll see me do this a lot throughout syphon to avoid the <blank> != null where possible. No need to change it here, just a note for the future. Looks good!

```dart
final unstableFeatures = version['unstable_features']  ??  {};
```

2022-04-01 16:33 UTC, merged