Feature/adjustments full screen images
syphon-org/syphon pull request #663
Opened 2022-04-09 00:53 UTC by Florian-Sabonchi

Share and download button added

2022-04-14 20:57 UTC, 0x1a8510f2 reviewed
Thanks for this work! A few minor comments.

2022-04-14 20:57 UTC, 0x1a8510f2 commented on lib/views/home/chat/media-full-screen.dart
> +                await Share.share('https://matrix.to/#/$roomId/$eventId');
Is there no existing function for this? If not, perhaps it's worth making one? I think constructing matrix links might be useful in a few places in the app.

2022-04-14 20:57 UTC, 0x1a8510f2 commented on lib/views/home/chat/media-full-screen.dart
> +        maxScale: PhotoViewComputedScale.covered * 2,
May be worth adding a comment here.

2022-04-14 20:57 UTC, 0x1a8510f2 commented on lib/views/home/chat/media-full-screen.dart
> +              color: Colors.white,
Will this be affected by the theme? I.e., could this become invisible in some themes? Might be worth making this and other hard coded colours here dynamic.

2022-04-15 09:14 UTC, EdGeraghty commented on lib/views/home/chat/media-full-screen.dart
> +              color: Colors.white,
You've a few options to play with in `Theme.of(context)`, which should do what you want

2022-04-15 12:58 UTC, Florian-Sabonchi commented on lib/views/home/chat/media-full-screen.dart
> +              color: Colors.white,
Maybe we should overhaul themes in general.

2022-04-15 12:59 UTC, Florian-Sabonchi commented on lib/views/home/chat/media-full-screen.dart
> +              color: Colors.white,
![Screenshot_20220415-145600_Syphon.png](https://user-images.githubusercontent.com/54689374/163573559-11e0d14d-bb4c-4cc6-b294-156faebf9888.png)

2022-04-15 13:00 UTC, Florian-Sabonchi commented on lib/views/home/chat/media-full-screen.dart
> +              color: Colors.white,
Changing the color of the title bar, for example, causes buttons to become invisible regardless of my change.

2022-04-15 13:01 UTC, Florian-Sabonchi commented on lib/views/home/chat/media-full-screen.dart
> +        maxScale: PhotoViewComputedScale.covered * 2,
Okay do you have a suggestion for a good comment?

2022-04-15 13:34 UTC, Florian-Sabonchi commented on lib/views/home/chat/media-full-screen.dart
> +                await Share.share('https://matrix.to/#/$roomId/$eventId');
I'm not sure if this is correct but I created a function fetchMessageUrl in media.dart

2022-04-15 13:41 UTC, 0x1a8510f2 commented on lib/views/home/chat/media-full-screen.dart
> +                await Share.share('https://matrix.to/#/$roomId/$eventId');
Looks good, though I'm not sure if `media.dart` is the right place for it. I'd put it somewhere more general. IIRC, there should be a global file with helper functions.

2022-04-15 13:45 UTC, 0x1a8510f2 commented on lib/views/home/chat/media-full-screen.dart
> +        maxScale: PhotoViewComputedScale.covered * 2,
Just something about what exactly this means and why this max scale was chosen. For example (don't know if this is actually the case): _`// Allow zooming in up to double the image size; anything beyond is usually pointless as the image becomes too pixelated`_.

2022-04-15 13:49 UTC, 0x1a8510f2 commented on lib/views/home/chat/media-full-screen.dart
> +              color: Colors.white,
This line should help: https://github.com/syphon-org/syphon/blob/dev/lib/views/widgets/appbars/appbar-avatar.dart#L104. Essentially, that always picks a colour which will contrast with the background.

2022-04-15 13:57 UTC, Florian-Sabonchi commented on lib/views/home/chat/media-full-screen.dart
> +              color: Colors.white,
Okay, thanks a lot i will look later on it. Thanks for your review

2022-04-17 10:48 UTC, EdGeraghty requested changes

2022-04-17 10:48 UTC, EdGeraghty commented on lib/views/home/chat/media-full-screen.dart
> +
Is something missing here?

2022-04-17 11:56 UTC, EdGeraghty commented on lib/views/home/chat/media-full-screen.dart
> +
See an example of how to add the "feature coming soon dialog" here: https://github.com/syphon-org/syphon/blob/e22719e3ee08fa31413ed8694464a785e95df49b/lib/store/alerts/actions.dart#L60 :)

2022-04-18 11:23 UTC, EdGeraghty reviewed
Lgtm!

2022-04-18 23:57 UTC, ereio requested changes

2022-04-18 23:57 UTC, ereio commented on lib/views/home/chat/media-full-screen.dart
> +                await Share.share(MatrixApi.fetchMessageUrl(roomId: roomId,eventId: eventId));
Let's rename this method to `generateMessageUrl` since the `fetch` keyword is reserved for remote calls inside the `MatrixApi`. 

Also wanted to see if you'd be willing to setup auto code formatting with the lint rules in your IDE to match what others and unify the look of the code as you contribute.

If you're using Vim as an editor, you should be able to install https://github.com/dart-lang/dart-vim-plugin and set `let g:dart_style_guide = 2` and `let g:dart_format_on_save = 1` and it should format automatically as you save files. Lmk if you don't use Vim, only mentioning after seeing some conversation about it in Syphon Dev. also a fan :)

Otherwise, LGTM! Will merge after this change rename either way 👍

2022-04-21 20:15 UTC, Florian-Sabonchi commented on lib/views/home/chat/media-full-screen.dart
> +                await Share.share(MatrixApi.fetchMessageUrl(roomId: roomId,eventId: eventId));
Hi thanks for the comment I use Android Studio for developing.

2022-04-21 21:45 UTC, ereio approved these changes

2022-04-21 21:46 UTC, merged