fix for issue #678
syphon-org/syphon pull request #701
Opened 2022-06-26 13:55 UTC by AdiAr11

### Types
- [ ] Fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking change which improves code quality - QA thoroughly )
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore (updates that would not affect or change the code involving the app itself)

### Changes

#### 🔮 Features
#### 🐛 Fixes
#### 🔒 Security 
#### 🛠 Performance
#### 📐 Refactoring

### Media (if applicable)
    
### QA

- [ ] Signup
- [ ] Login
- [ ] Logout
- [ ] Unencrypted Chat 
- [ ] Encrypted Chat 
- [ ] Group Chats
- [ ] Profile Changes
- [ ] Theming Changes
- [ ] Force Kill and Restart

### Final Checklist
 
- [ ] All associated issues have been linked to PR
- [ ] All necessary changes made to the documentation
- [ ] Parties interested in these changes have been notified
- [ ] Linter has been run on all code in the PR

2022-06-26 14:17 UTC, EdGeraghty requested changes

2022-06-26 14:17 UTC, EdGeraghty commented on lib/views/home/chat/widgets/chat-input.dart
> +  }
May I recommend you split this method into two?

`checkPhotoPermission` implies returning a boolean to me, the actual functionality of the method is not obvious from the name

2022-06-26 14:17 UTC, EdGeraghty commented on lib/views/home/chat/widgets/chat-input.dart
> +                            onPress: () => checkPhotoPermission(),
I'd move the functionality in here

2022-06-26 16:25 UTC, AdiAr11 commented on lib/views/home/chat/widgets/chat-input.dart
> +                            onPress: () => checkPhotoPermission(),
Okay, I'll make these changes 😀

2022-06-26 17:13 UTC, EdGeraghty commented on lib/views/home/chat/widgets/chat-input.dart
> +                            onPress: () => checkPhotoPermission(),
Perfect!

2022-06-26 17:17 UTC, EdGeraghty commented on lib/views/home/chat/widgets/chat-input.dart
> +  }
Perhaps something like `hasPhotoPermission` may be even more explicit

2022-06-28 21:11 UTC, EdGeraghty requested changes

2022-06-28 21:11 UTC, EdGeraghty commented on lib/views/home/chat/widgets/chat-input.dart
> +                                openAppSettings();
It's probably a good idea to warn the user that you're about to throw them to the app settings, and to tell them why.

Search for `showDialog` in the codebase to see how to add a warning - and if you're going to add text, that seems like a great time to add something to our internationalisation (i18n) library!

2022-06-28 21:12 UTC, EdGeraghty commented
Sorry for the faff - had a realisation after setting ready for review!

2022-06-29 10:32 UTC, EdGeraghty commented on lib/views/home/chat/widgets/chat-input.dart
> +                                openAppSettings();
Perfect!

2022-06-30 12:45 UTC, EdGeraghty commented on lib/global/strings.dart
> +  static final contentPhotoPermission = tr('content-dialog-photo-permission');
Good work on the i18n front!

2022-06-30 12:45 UTC, EdGeraghty commented on lib/views/home/chat/widgets/chat-input.dart
> +      showDialog(
I'm not so sure we should differentiate here, we should probably just use showDialog() regardless of platform.

Speaking of which, have you tried this on a desktop build?

2022-06-30 12:45 UTC, EdGeraghty commented on lib/views/home/chat/widgets/chat-input.dart
> +                                showDialogForPhotoPermission(context);
Unambiguous. Nice.

2022-06-30 12:53 UTC, AdiAr11 commented on lib/global/strings.dart
> +  static final contentPhotoPermission = tr('content-dialog-photo-permission');
Thank you !

2022-06-30 12:54 UTC, AdiAr11 commented on lib/views/home/chat/widgets/chat-input.dart
> +      showDialog(
Okay, I'll use the showDialog function only. 
Also I haven't tried the desktop build yet

2022-07-08 12:12 UTC, EdGeraghty approved these changes
👍

2022-08-25 03:04 UTC, ereio approved these changes
Awesome work, thanks so much for contributing! 👍 :)

2022-08-25 03:05 UTC, merged

2022-08-25 05:24 UTC, AdiAr11 commented
> Awesome work, thanks so much for contributing! 👍 :)

Thank you so much !!