[Feature] Check GitHub for updates
syphon-org/syphon pull request #712
Opened 2022-07-30 10:26 UTC by EdGeraghty

### Types
- [ ] Fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking change which improves code quality - QA thoroughly )
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore (updates that would not affect or change the code involving the app itself)

### Changes

#### 🔮 Features
Opt-in Advanced Setting to poll GitHub for updated releases
#### 🐛 Fixes
#### 🔒 Security 
#### 🛠 Performance
#### 📐 Refactoring

### Media (if applicable)
    
### QA

- [ ] Signup
- [ ] Login
- [ ] Logout
- [ ] Unencrypted Chat 
- [ ] Encrypted Chat 
- [ ] Group Chats
- [ ] Profile Changes
- [ ] Theming Changes
- [ ] Force Kill and Restart

### Final Checklist
 
- [ ] All associated issues have been linked to PR
- [ ] All necessary changes made to the documentation
- [ ] Parties interested in these changes have been notified
- [ ] Linter has been run on all code in the PR

2022-07-30 13:13 UTC, EdGeraghty commented
Trying to work out the best place to put the check itself 🤔

2022-07-30 18:06 UTC, EdGeraghty commented
I've done an initial implementation, which needs a bit of work. Comments/advise welcome!

2022-08-13 19:30 UTC, EdGeraghty commented on lib/views/home/home-screen.dart
> +      if (UpdateChecker.updateAvailable) {}
I'm wondering whether to build a new route for this, or is that overkill?

2022-09-11 19:11 UTC, ereio commented on lib/views/home/home-screen.dart
> +      if (UpdateChecker.updateAvailable) {}
A new route / widget in the app? Sure! we could also make a dialog widget and dispatch it popping up here instead right?

2022-09-11 19:14 UTC, EdGeraghty commented on lib/views/home/home-screen.dart
> +      if (UpdateChecker.updateAvailable) {}
Yep! Again, feel free to commit as suited

2022-09-11 19:18 UTC, ereio requested changes

2022-09-11 19:18 UTC, ereio commented on pubspec.lock
> -    source: hosted
oh make sure not to delete the pubspec.lock. Needed for pinning dependency versions!

2022-09-11 19:30 UTC, ereio commented
I'll add the dialog here in a bit

Was wondering if we could add another saved state variable to allow for dismissing the dialog without it popping up each time
Ideally we could just save an `updateAcknowledgedTimestamp` and if that timestamp is greater than the update time, it won't appear

Happy to add that too unless you'd like / want to do the work for that :)

Once both are added, I'll approve! good work! 🚀

2022-09-11 19:34 UTC, EdGeraghty commented on lib/global/libs/updater/update-check.dart
> +  static DateTime nextCheckNotBefore = DateTime.utc(1970);
@ereio you can probably use these variables here for the state stuff mentioned in the review comment

2022-09-11 19:38 UTC, EdGeraghty commented on lib/global/libs/updater/update-check.dart
> +    nextCheckNotBefore = lastChecked!.add(Duration(hours: 18));
18 hours was a completely arbitrary, unilateral choice on my part. Feel free to adjust as you see fit.

2022-09-11 21:34 UTC, ereio commented
@EdGeraghty this should work now, if you were testing before would you mind checking this out?

Also what are you thoughts on a redirect vs. downloading the APK directly? I've added a redirect right now and I think that's fine but happy to change it

2022-09-11 22:34 UTC, EdGeraghty commented
If we leave it going to the releases page it'll cover desktop builds too 🎉

2022-12-04 22:38 UTC, ereio commented
If we're happy without the desktop portion of this working, are we ok to merge this for now? @EdGeraghty

2022-12-04 22:38 UTC, ereio approved these changes, later dismissed

2025-02-10 13:11 UTC, closed without merging