[feature] take picture directly from camera (issue #708)
syphon-org/syphon pull request #719
Opened 2022-08-21 13:40 UTC by AdiAr11

### Types
- [ ] Fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking change which improves code quality - QA thoroughly )
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore (updates that would not affect or change the code involving the app itself)

### Changes

#### 🔮 Features
#### 🐛 Fixes
#### 🔒 Security 
#### 🛠 Performance
#### 📐 Refactoring

### Media (if applicable)
    
### QA

- [ ] Signup
- [ ] Login
- [ ] Logout
- [ ] Unencrypted Chat 
- [ ] Encrypted Chat 
- [ ] Group Chats
- [ ] Profile Changes
- [ ] Theming Changes
- [ ] Force Kill and Restart

### Final Checklist
 
- [ ] All associated issues have been linked to PR
- [ ] All necessary changes made to the documentation
- [ ] Parties interested in these changes have been notified
- [ ] Linter has been run on all code in the PR

2022-09-11 19:04 UTC, ereio requested changes
Want to figure out how to keep the 18 target version and just a few style issues.

Let's fix the style issues / add those styles to the styleguide and fork the camera lib if necessary

2022-09-11 19:04 UTC, ereio commented on android/app/build.gradle
> -        minSdkVersion 18
I'm considering forking the camera lib and lowering it. We can check SDK version before attempting initialization to avoid incompatibility but allow building at a lower target

2022-09-13 13:39 UTC, AdiAr11 commented on android/app/build.gradle
> -        minSdkVersion 18
Yes maybe we can try to lower the minSdk requirement in the camera package. I had to increase it because that package supports sdk 21+. I'll also try researching.

2022-09-13 13:39 UTC, AdiAr11 commented on lib/views/home/chat/take_picture_screen.dart
> +class TakePictureScreenState extends State<TakePictureScreen> {
I'm sorry, CameraScreen is more apt. I'll change it.

2022-09-13 13:41 UTC, AdiAr11 commented
Hi @ereio !! sorry, been a little busy with work. I will make the required changes in the weekend.

2022-09-13 15:29 UTC, EdGeraghty commented on lib/views/home/chat/take_picture_screen.dart
> +    else {
This is something I'll also keep in mind, as someone who traditionally prefers
```
if (expression) {
// ...
}
else {
// ...
}
```

2022-09-13 18:45 UTC, ereio commented
> Hi @ereio !! sorry, been a little busy with work. I will make the required changes in the weekend.

no worries, and no rush! thanks for all your hard work :)

2022-09-13 18:46 UTC, ereio commented on lib/views/home/chat/take_picture_screen.dart
> +class TakePictureScreenState extends State<TakePictureScreen> {
No need to be sorry, was genuinely asking! Sounds good!

2022-09-17 09:13 UTC, AdiAr11 commented
Hi @ereio , I have made the changes. Also I was searching if we can implement this functionality without increasing the minSdk. I think there is a workaround. 
https://github.com/flutter/flutter/issues/19083

2022-09-26 01:44 UTC, 0x1a8510f2 commented on android/app/build.gradle
> -        minSdkVersion 18
FWIW, I found some numbers on the Android versions currently in use:

As of November 2021, devices with API level <21 accounted for ≈2% of the Android user base according to https://www.androidpolice.com/googles-latest-android-version-distribution-numbers-show-11-in-dead-heat-with-10/

According to https://9to5google.com/2022/05/20/android-2022-distribution-numbers-chart/ this dropped to ≈1.4% as of May 2022.

Using the numbers from the latter, going from API level 18 to API level 21 means we lose support for 1.1% of Android users over the 0.3% who are currently below API level 18 (and hence, are unsupported already).

Assuming 3bln Android devices per https://www.theverge.com/2021/5/18/22440813/android-devices-active-number-smartphones-google-2021 going from SDK 18 to 21 will drop support for ≈33mln devices on top of those which we already don't support.

(Note that most of these figures are somewhat outdated).

2022-09-27 06:13 UTC, AdiAr11 commented on android/app/build.gradle
> -        minSdkVersion 18
Wow, amazing observation. But do we know how many of those between API 18 and 21 actually use this app? i checked API 21 is android 5, which is now kinda old. My device is 6 years old, and it runs on android 7, and still there are quite a few design issues. Like the layout doesn't fit properly.

2022-09-27 13:28 UTC, 0x1a8510f2 commented on android/app/build.gradle
> -        minSdkVersion 18
No idea, I don't have access to the Syphon gplay console (which would still not give an accurate representation because people might install Syphon directly from github or fdroid and we don't have analytics).

Personally, given that the number of devices below Android 5 is dropping in general, I wouldn't mind the minimum API change considering that keeping it down will likely make maintenance a fair bit more difficult in general. At the same time, Syphon is meant to be as universal and accessible as possible so I think this would probably need some more discussion on the tradeoffs we would be making.

2022-09-27 14:15 UTC, AdiAr11 commented on android/app/build.gradle
> -        minSdkVersion 18
Right, completely agree !!

2022-12-04 22:31 UTC, ereio commented on android/app/build.gradle
> -        minSdkVersion 18
Totally missed this and completely agree. If it's truly that low now, I'm fine with dropping support! We always have linux as a fallback which should still run on very old desktops

2022-12-04 22:33 UTC, ereio approved these changes, later dismissed
Awesome job @AdiAr11! and thanks @0x1a8510f2 for addressing the issue so diligently!

2022-12-04 22:35 UTC, ereio approved these changes

2022-12-04 22:35 UTC, merged

2022-12-05 04:59 UTC, AdiAr11 commented
Thank you so much @ereio !